version: 0.2

phases:
  install:
    runtime-versions:
       java: corretto8
       docker: 18
  pre_build:
    commands:
       - java -version
       - mvn -version
       - docker login -u nareshit67 -p nareshit67
  build:
    commands:
      - mvn clean install
      - docker build -t nareshit67/cicd:semanalysis .
      - docker push nareshit67/cicd:semanalysis
      - docker run -d-p 8080 nareshit67/cicd:semanalysis
artifacts:
  files:
    - target/jb-hello-world-maven-0.2.0.jar
